[user]
name = "langurmonkey"
email = "me@tonisagrista.com"

[signing]
behavior = "own"
backend = "gpg"
key = "448C2B189756743013D5F7C22FD2A59C1D734C1F"

[ui]
paginate = "auto"
default-command = "log"

[aliases]
# Updates the main bookmark.
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
# Shows commits on the working copy commit's bookmark compared to master.
l = ["log", "-r", "(master..@):: | (master..@)-"]

[revsets]
log = "root().."
